### ISSUE TITLE
Some masking text snippets 

### ISSUE THREAD

**Issue by inolopesm** [JuninhoFreitas/useful-nodejs#1]
To contribute to this repository, I start with this PR to create some snippets to mask text. For example:

- maskBrazilianIndividualRegistration function
- maskBrazilianLegalEntityRegistration function
- maskBrazilianPhoneNumber function

I used google translator to write this text, so sorry for my english

**Comment by JuninhoFreitas** [comment]
@inolopesm 
maskBrazilianPhoneNumber added,
with maskBrazilianIndividualRegistration u mean CPF?
and entityRegistration, CNPJ?

**Comment by inolopesm** [comment]
> @inolopesm maskBrazilianPhoneNumber added, with maskBrazilianIndividualRegistration u mean CPF? and entityRegistration, CNPJ?

Yep, CPF and CNPJ
